version: "3.7"
name: gameplan
services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine
    command: redis-server --save 20 1
    volumes:
      - redis-data:/data

  frappe:
    image: frappe/bench:latest
    command: bash /tmp/init/init.sh
    environment:
      SHELL: /bin/bash
      MARIADB_ROOT_PASSWORD: 123
      BENCH_ADMIN_PASSWORD: admin
      BENCH_DEVELOPER_MODE: 1
      BENCH_MUTE_EMAILS: 1
    working_dir: /home/frappe
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./init/:/tmp/init/
      - frappe-bench-data:/home/frappe/
    ports:
      - 8000:8000
      - 9000:9000

volumes:
  mariadb-data:
    driver: local
  redis-data:
    driver: local
  frappe-bench-data:
    driver: local